version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: jean85/pretty-package-versions
    versions:
    - "> 2.0.2, < 2.1"
  - dependency-name: phpstan/phpstan
    versions:
    - "> 0.12.74, < 0.13"
  - dependency-name: phpstan/phpstan-phpunit
    versions:
    - "> 0.12.11, < 0.13"
  - dependency-name: phpunit/phpunit
    versions:
    - "> 9.2.3, < 9.3"
  - dependency-name: phpunit/phpunit
    versions:
    - "> 9.3.1, < 9.4"
  - dependency-name: phpunit/phpunit
    versions:
    - "> 9.5.0, < 9.6"
  - dependency-name: php-vfs/php-vfs
    versions:
    - "> 1.4.1, < 1.5"
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.35
  - dependency-name: jean85/pretty-package-versions
    versions:
    - 1.6.0
